# Generated by Django 5.0 on 2023-12-13 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FileBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('idG', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MediMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msg_user', models.CharField(max_length=200)),
                ('msg_title', models.CharField(max_length=200)),
                ('msg_date', models.DateField(auto_now=True)),
                ('msg_time', models.TimeField(auto_now=True)),
                ('msg_content', models.CharField(max_length=1000)),
                ('msg_jih', models.CharField(max_length=300)),
                ('msg_procedures', models.CharField(max_length=1000)),
                ('msg_newseditor', models.CharField(max_length=200)),
                ('msg_editdate', models.DateField(auto_now=True)),
                ('msg_receiveteam', models.BooleanField(default=False)),
                ('msg_secretary', models.BooleanField(default=False)),
                ('msg_Minister', models.BooleanField(default=False)),
                ('msg_published', models.BooleanField(default=False)),
                ('msg_tracking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('msg_fileBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_media_app.filebook')),
                ('msg_governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_media_app.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='MediaIfad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idifada', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ifada_title', models.CharField(max_length=300)),
                ('ifada_path', models.CharField(max_length=1000)),
                ('id_relb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_media_app.medimessages')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idattch', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('attch_title', models.CharField(max_length=300)),
                ('attch_path', models.CharField(max_length=1000)),
                ('id_relt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_media_app.medimessages')),
            ],
        ),
    ]
