# Generated by Django 4.2.8 on 2023-12-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaatt',
            name='id_relt',
            field=models.ForeignKey(db_column='id_relt_id', on_delete=django.db.models.deletion.CASCADE, to='security_media_app.medimessages'),
        ),
        migrations.AlterField(
            model_name='mediaifad',
            name='id_relb',
            field=models.ForeignKey(db_column='id_relb_id', on_delete=django.db.models.deletion.CASCADE, to='security_media_app.medimessages'),
        ),
    ]
